# Используем BERT впервые

Источник: [Jay Alamar](http://jalammar.github.io/a-visual-guide-to-using-bert-for-the-first-time/)


<img src="https://jalammar.github.io/images/distilBERT/bert-distilbert-sentence-classification.png" />

In this notebook, we will use pre-trained deep learning model to process some text. We will then use the output of that model to classify the text. The text is a list of sentences from film reviews. And we will calssify each sentence as either speaking "positively" about its subject of "negatively".

## Models: Sentence Sentiment Classification
Our goal is to create a model that takes a sentence (just like the ones in our dataset) and produces either 1 (indicating the sentence carries a positive sentiment) or a 0 (indicating the sentence carries a negative sentiment). We can think of it as looking like this:

<img src="https://jalammar.github.io/images/distilBERT/sentiment-classifier-1.png" />

Under the hood, the model is actually made up of two model.

* DistilBERT processes the sentence and passes along some information it extracted from it on to the next model. DistilBERT is a smaller version of BERT developed and open sourced by the team at HuggingFace. It’s a lighter and faster version of BERT that roughly matches its performance.
* The next model, a basic Logistic Regression model from scikit learn will take in the result of DistilBERT’s processing, and classify the sentence as either positive or negative (1 or 0, respectively).

The data we pass between the two models is a vector of size 768. We can think of this of vector as an embedding for the sentence that we can use for classification.


<img src="https://jalammar.github.io/images/distilBERT/distilbert-bert-sentiment-classifier.png" />

## Dataset
The dataset we will use in this example is [SST2](https://nlp.stanford.edu/sentiment/index.html), which contains sentences from movie reviews, each labeled as either positive (has the value 1) or negative (has the value 0):


<table class="features-table">
  <tr>
    <th class="mdc-text-light-green-600">
    sentence
    </th>
    <th class="mdc-text-purple-600">
    label
    </th>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      a stirring , funny and finally transporting re imagining of beauty and the beast and 1930s horror films
    </td>
    <td class="mdc-bg-purple-50">
      1
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      apparently reassembled from the cutting room floor of any given daytime soap
    </td>
    <td class="mdc-bg-purple-50">
      0
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      they presume their audience won't sit still for a sociology lesson
    </td>
    <td class="mdc-bg-purple-50">
      0
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      this is a visually stunning rumination on love , memory , history and the war between art and commerce
    </td>
    <td class="mdc-bg-purple-50">
      1
    </td>
  </tr>
  <tr>
    <td class="mdc-bg-light-green-50" style="text-align:left">
      jonathan parker 's bartleby should have been the be all end all of the modern office anomie films
    </td>
    <td class="mdc-bg-purple-50">
      1
    </td>
  </tr>
</table>

## Installing the transformers library
Let's start by installing the huggingface transformers library so we can load our deep learning NLP model.

In [94]:
!pip install transformers

In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
import warnings
warnings.filterwarnings('ignore')

## Данные

In [0]:
df = pd.read_csv('https://github.com/clairett/pytorch-sentiment-classification/raw/master/data/SST2/train.tsv', delimiter='\t', header=None)

In [97]:
df.head()

0  1
0  a stirring , funny and finally transporting re...  1
1  apparently reassembled from the cutting room f...  0
2  they presume their audience wo n't sit still f...  0
3  this is a visually stunning rumination on love...  1
4  jonathan parker 's bartleby should have been t...  1

In [98]:
df.shape

(6920, 2)

Возьмём первые 2,000.

In [0]:
batch_1 = df[:2000]

Баланс классов:

In [100]:
batch_1[1].value_counts()

1    1041
0     959
Name: 1, dtype: int64

## Loading the Pre-trained BERT model
Let's now load a pre-trained BERT model. 

In [0]:
# For DistilBERT:
model_class, tokenizer_class, pretrained_weights = (ppb.DistilBertModel, ppb.DistilBertTokenizer, 'distilbert-base-uncased')

## Want BERT instead of distilBERT? Uncomment the following line:
#model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

# Load pretrained model/tokenizer
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

Right now, the variable `model` holds a pretrained distilBERT model -- a version of BERT that is smaller, but much faster and requiring a lot less memory.


### Токенизация
Our first step is to tokenize the sentences -- break them up into word and subwords in the format BERT is comfortable with.


In [0]:
tokenized = batch_1[0].apply(lambda x: tokenizer.encode(x, add_special_tokens=True))

In [108]:
tokenized[:5]

0    [101, 1037, 18385, 1010, 6057, 1998, 2633, 182...
1    [101, 4593, 2128, 27241, 23931, 2013, 1996, 62...
2    [101, 2027, 3653, 23545, 2037, 4378, 24185, 10...
3    [101, 2023, 2003, 1037, 17453, 14726, 19379, 1...
4    [101, 5655, 6262, 1005, 1055, 12075, 2571, 376...
Name: 0, dtype: object

In [105]:
df.iloc[0][0]

'a stirring , funny and finally transporting re imagining of beauty and the beast and 1930s horror films'

In [106]:
df.iloc[1][0]

'apparently reassembled from the cutting room floor of any given daytime soap'

In [113]:
tokenizer.vocab['[CLS]']

101

In [0]:
id2token = {ind:tok for tok, ind in tokenizer.vocab.items()}

In [115]:
id2token[101]

'[CLS]'

In [117]:
tokenizer.wordpiece_tokenizer.tokenize('a stirring , funny and finally')

['a', 'stirring', ',', 'funny', 'and', 'finally']

In [119]:
tokenizer.decode([101, 1037, 18385, 1010, 6057, 1998, 2633])

'[CLS] a stirring, funny and finally'

In [121]:
tokenizer.wordpiece_tokenizer.tokenize('pythonista')

['python', '##ista']

In [123]:
tokenizer.wordpiece_tokenizer.tokenize('cowork')

['cow', '##or', '##k']

<img src="https://jalammar.github.io/images/distilBERT/bert-distilbert-tokenization-2-token-ids.png" />

### Padding
Выравниваем предложения по длине с помощью нулевых токенов.

In [0]:
# находим самое длинное предложение
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)

# заполняем обучающие данные, где не хватает длины до максимума -- добавляем нули
padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])

In [126]:
np.array(padded).shape

(2000, 59)

### Masking

Теперь создаём отдельную переменную, чтобы сказать берту, что надо игнорировать паддинг при подсчёте attention.

In [127]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape

(2000, 59)

In [128]:
len(tokenized[0])

20

In [17]:
attention_mask[0]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [130]:
sum(attention_mask[0])

20

## Используем BERT

Функция `model()` прогоняет предложения через BERT.

In [0]:
input_ids = torch.tensor(padded)  
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
    last_hidden_states = model(input_ids, attention_mask=attention_mask)

Let's slice only the part of the output that we need. That is the output corresponding the first token of each sentence. The way BERT does sentence classification, is that it adds a token called `[CLS]` (for classification) at the beginning of every sentence. The output corresponding to that token can be thought of as an embedding for the entire sentence.

<img src="https://jalammar.github.io/images/distilBERT/bert-output-tensor-selection.png" />

Берём оттуда только представления первого токена -- `[CLS]`. Это представление и будет нашими признаками.

In [134]:
last_hidden_states[0].shape

torch.Size([2000, 59, 768])

In [0]:
features = last_hidden_states[0][:,0,:].numpy()

In [136]:
features.shape

(2000, 768)

In [138]:
len(features[0])

768

Метки:

In [0]:
labels = batch_1[1]

## LogReg на фичах из BERT
Let's now split our datset into a training set and testing set (even though we're using 2,000 sentences from the SST2 training set).

In [0]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels)

We now train the LogisticRegression model. If you've chosen to do the gridsearch, you can plug the value of C into the model declaration (e.g. `LogisticRegression(C=5.2)`).

In [142]:
lr_clf = LogisticRegression()
lr_clf.fit(train_features, train_labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Оцениваем результат
Accuracy на тесте:

In [143]:
lr_clf.score(test_features, test_labels)

0.84

In [0]:
from sklearn.metrics import classification_report

In [147]:
print(classification_report(lr_clf.predict(test_features), test_labels))

              precision    recall  f1-score   support

           0       0.83      0.85      0.84       245
           1       0.85      0.83      0.84       255

    accuracy                           0.84       500
   macro avg       0.84      0.84      0.84       500
weighted avg       0.84      0.84      0.84       500



Сравним с DummyClassifier

In [151]:
from sklearn.dummy import DummyClassifier
clf = DummyClassifier()

scores = cross_val_score(clf, train_features, train_labels)
print("Dummy classifier score: %0.3f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Dummy classifier score: 0.526 (+/- 0.03)


А что насчёт луших классификаторов?

## Proper SST2 scores
For reference, the [highest accuracy score](http://nlpprogress.com/english/sentiment_analysis.html) for this dataset is currently **96.8**. DistilBERT can be trained to improve its score on this task – a process called **fine-tuning** which updates BERT’s weights to make it achieve a better performance in this sentence classification task (which we can call the downstream task). The fine-tuned DistilBERT turns out to achieve an accuracy score of **90.7**. The full size BERT model achieves **94.9**.



And that’s it! That’s a good first contact with BERT. The next step would be to head over to the documentation and try your hand at [fine-tuning](https://huggingface.co/transformers/examples.html#glue). You can also go back and switch from distilBERT to BERT and see how that works.

### Как использовать BERT в качестве эмбеддингов слов

In [0]:
s1 = 'wall street'
s2 = 'i broke the wall'
s3 = 'another brick in the wall'

In [0]:
s1_tok = tokenizer.encode(s1)
s2_tok = tokenizer.encode(s2)
s3_tok = tokenizer.encode(s3)

In [185]:
tokenizer.vocab['wall']

2813

In [186]:
s1_tok.index(2813)

1

In [187]:
s2_tok.index(2813)

4

In [188]:
s3_tok.index(2813)

5

In [0]:
with torch.no_grad():
    last_hidden_states1 = model(torch.tensor([s1_tok]))
    last_hidden_states2 = model(torch.tensor([s2_tok]))
    last_hidden_states3 = model(torch.tensor([s3_tok]))

In [0]:
bank1_emb = last_hidden_states1[0][:,1,:]
bank2_emb = last_hidden_states2[0][:,4,:]
bank3_emb = last_hidden_states3[0][:,5,:]

Теперь посчитаем расстояние:

In [0]:
from sklearn.metrics.pairwise import cosine_similarity

In [191]:
cosine_similarity(bank1_emb.numpy(), bank2_emb.numpy())

array([[0.4556053]], dtype=float32)

In [192]:
cosine_similarity(bank1_emb.numpy(), bank3_emb.numpy())

array([[0.45279628]], dtype=float32)

In [193]:
cosine_similarity(bank2_emb.numpy(), bank3_emb.numpy())

array([[0.86112154]], dtype=float32)

### Для IMDB

## Русский -- DeepPavlov

In [0]:
tokenizer = ppb.AutoTokenizer.from_pretrained("DeepPavlov/rubert-base-cased")

In [0]:
model = ppb.AutoModelWithLMHead.from_pretrained("DeepPavlov/rubert-base-cased")

In [5]:
tokenizer.wordpiece_tokenizer.tokenize('Русский текст')

['Русский', 'текст']

In [6]:
tokenizer.wordpiece_tokenizer.tokenize('печенюшка')

['печен', '##юшка']

#### Классификация ленты

In [200]:
! wget -O lenta-ru-train.csv https://www.dropbox.com/s/kdupcw1llbdbqwl/lenta-ru-train.csv?dl=0

--2020-04-25 14:38:09--  https://www.dropbox.com/s/kdupcw1llbdbqwl/lenta-ru-train.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.9.1, 2620:100:601f:1::a27d:901
Connecting to www.dropbox.com (www.dropbox.com)|162.125.9.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/kdupcw1llbdbqwl/lenta-ru-train.csv [following]
--2020-04-25 14:38:09--  https://www.dropbox.com/s/raw/kdupcw1llbdbqwl/lenta-ru-train.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc445243463ed73e23a0e24ce3ed.dl.dropboxusercontent.com/cd/0/inline/A2jsfT8GC89WKu1zRkjyjv4a5tYFXLOrvbxMM7GQPyfnRsplcZOOjaXEiefLbaz-VXAPDd8vWapNNdTJyp5C37yDNd9Ca47pEYFnfveiHerjgWYoDET9ElSLPGJ8W4CiAFs/file# [following]
--2020-04-25 14:38:09--  https://uc445243463ed73e23a0e24ce3ed.dl.dropboxusercontent.com/cd/0/inline/A2jsfT8GC89WKu1zRkjyjv4a5tYFXLOrvbxMM7GQPyfnRsplcZOOjaXEiefLbaz-VXAPDd8vWapNNdTJyp5C37yDNd9

In [0]:
df_lenta = pd.read_csv('lenta-ru-train.csv')

In [7]:
df_lenta.head()

title  ... topic_label
0  Инфляция в январе 2006 года составит 2,6 процента  ...           0
1      Никита Михалков учредил День российского кино  ...           3
2    Марко Матерацци вернется в строй к матчу с ЦСКА  ...           1
3            Определены лауреаты премии "Книга года"  ...           3
4  Гол Роналду со штрафного спас португальцев от ...  ...           1

[5 rows x 4 columns]

In [0]:
df_lenta_batch = df_lenta[:10000]

In [0]:
from tqdm import tqdm

In [0]:
tqdm.pandas()

In [11]:
lenta_tokenized = df_lenta_batch.title.progress_apply(lambda x: tokenizer.encode(x, add_special_tokens=True))

100%|██████████| 10000/10000 [00:02<00:00, 4230.04it/s]


In [0]:
max_len = max([len(sent) for sent in lenta_tokenized.values])

In [13]:
max_len

32

In [0]:
# заполняем обучающие данные, где не хватает длины до максимума -- добавляем нули
padded = np.array([i + [0]*(max_len-len(i)) for i in lenta_tokenized.values])

In [15]:
padded.shape

(10000, 32)

In [20]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape

(10000, 32)

In [0]:
features = []
with torch.no_grad():
  for i in tqdm(range(0, 10000, 100)):
    padded_bit = padded[i: (i + 100)]
    attention_mask_bit = attention_mask[i: (i + 100)] 
    bert_input = torch.tensor(padded_bit)
    attention_mask_bit = torch.tensor(attention_mask_bit)
    last_hidden_states = model(bert_input, attention_mask=attention_mask_bit)
    features.append(last_hidden_states[0][:,0,:].numpy())

 15%|█▌        | 15/100 [02:16<12:58,  9.16s/it]

In [0]:
features = last_hidden_states[0][:,0,:]

In [0]:
train_features, test_features, train_labels, test_labels = train_test_split(features, labels)

In [0]:
lr = LogisticRegression()